
development:
  host: localhost
  adapter: postgis
  encoding: unicode
  database: voolta
  pool: 5
  username: postgres
  password: <%= ENV['PSQL_PASSWD'] %>

test:
  host: localhost
  adapter: postgis
  encoding: unicode
  database: voolta_test
  pool: 5
  username: postgres
  password: <%= ENV['PSQL_PASSWD'] %>
  
production:
  database: voolta
  adapter: postgis
  encoding: unicode
  username: spalatin
  pool: 5
  password: