
development:
  host: localhost
  adapter: postgis
  encoding: unicode
  database: voolta
  pool: 5
  username: spalatin
  password: 

test:
  adapter: postgis
  database: bungy_test
  pool: 5
  username: postgres

production:
  database: voolta
  adapter: postgis
  encoding: unicode
  username: spalatin
  pool: 5
  password: